(function () {
  window.JOB_DATA = [
    {
      id: "job-1",
      title: "SDE Intern",
      company: "Amazon India",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Java", "Data Structures", "Algorithms", "AWS"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://www.amazon.jobs/en/jobs/sde-intern-blr",
      description:
        "Work with experienced engineers to build and improve internal tools used across Amazon India.\nCollaborate on feature development, code reviews, and testing for production services.\nGain exposure to distributed systems, cloud services, and large-scale architecture.\nThis internship is designed for final-year students with strong fundamentals.",
    },
    {
      id: "job-2",
      title: "Graduate Engineer Trainee",
      company: "Infosys",
      location: "Mysuru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "SQL", "Spring Boot"],
      source: "Naukri",
      postedDaysAgo: 3,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.infosys.com/graduate-engineer-trainee",
      description:
        "Join the Infosys training program and work on real client delivery projects.\nContribute to backend services, integration tasks, and production support.\nWork closely with mentors to improve coding standards and design skills.\nIdeal for recent graduates with strong problem-solving abilities.",
    },
    {
      id: "job-3",
      title: "Frontend Intern",
      company: "Flipkart",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["JavaScript", "React", "HTML", "CSS"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://www.flipkartcareers.com/frontend-intern",
      description:
        "Assist in building and polishing customer-facing shopping experiences.\nWork with design and product teams to translate Figma designs into reliable UI.\nImprove accessibility, performance, and responsiveness of existing components.\nSuitable for candidates with strong fundamentals in modern JavaScript.",
    },
    {
      id: "job-4",
      title: "Junior Backend Developer",
      company: "Razorpay",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Node.js", "PostgreSQL", "REST APIs", "Microservices"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "6–10 LPA",
      applyUrl: "https://razorpay.com/careers/junior-backend-developer",
      description:
        "Build and maintain microservices that power Razorpay's payment workflows.\nWork on APIs, background jobs, and internal tooling with a focus on reliability.\nCollaborate with cross-functional teams to deliver features end to end.\nIdeal for developers with prior internship or 1+ year backend experience.",
    },
    {
      id: "job-5",
      title: "Data Analyst Intern",
      company: "Swiggy",
      location: "Bengaluru",
      mode: "Remote",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Python", "Tableau"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://careers.swiggy.com/data-analyst-intern",
      description:
        "Support analytics projects that improve restaurant and delivery partner performance.\nWork with large datasets to create dashboards and operational reports.\nPartner with analysts and product managers to define metrics and insights.\nBest suited for final-year students comfortable working with data tools.",
    },
    {
      id: "job-6",
      title: "QA Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Manual Testing", "Test Cases", "Selenium"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://www.zoho.com/careers/qa-intern",
      description:
        "Execute test plans for web and mobile applications in the Zoho suite.\nDocument defects clearly and work with developers to validate fixes.\nLearn to design smoke, regression, and exploratory test scenarios.\nOpen to graduates with good attention to detail and communication skills.",
    },
    {
      id: "job-7",
      title: "React Developer (1-3)",
      company: "Freshworks",
      location: "Chennai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "TypeScript", "Redux", "REST APIs"],
      source: "LinkedIn",
      postedDaysAgo: 6,
      salaryRange: "6–10 LPA",
      applyUrl: "https://careers.freshworks.com/react-developer",
      description:
        "Develop and maintain customer-facing modules for SaaS products.\nWrite clean, well-tested React components that integrate with backend services.\nCollaborate with designers and product managers to refine user journeys.\nSuitable for developers with at least one year of professional UI experience.",
    },
    {
      id: "job-8",
      title: "Python Developer (Fresher)",
      company: "TCS",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "Django", "REST APIs"],
      source: "Naukri",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://www.tcs.com/careers/python-developer-fresher",
      description:
        "Work on internal tools and automation workflows using Python.\nAssist in building APIs and small services using Django and related frameworks.\nParticipate in code reviews, documentation, and integration tasks.\nGood fit for freshers comfortable with scripting and basic web concepts.",
    },
    {
      id: "job-9",
      title: "Java Developer (0-1)",
      company: "Wipro",
      location: "Pune",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring", "REST", "Git"],
      source: "Indeed",
      postedDaysAgo: 3,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.wipro.com/java-developer-0-1",
      description:
        "Support development and maintenance of Java-based enterprise applications.\nFix bugs, implement minor enhancements, and write unit tests.\nWork alongside senior developers to understand design patterns and best practices.\nIdeal for early-career engineers with strong Java fundamentals.",
    },
    {
      id: "job-10",
      title: "Junior Backend Developer",
      company: "CRED",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Go", "PostgreSQL", "Kafka", "Microservices"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "10–18 LPA",
      applyUrl: "https://careers.cred.club/junior-backend-developer",
      description:
        "Contribute to services that power credit, rewards, and member experiences.\nBuild resilient APIs and background jobs with a focus on observability.\nParticipate in design discussions, incident reviews, and capacity planning.\nBest suited for engineers with prior startup or fintech experience.",
    },
    {
      id: "job-11",
      title: "SDE Intern",
      company: "PhonePe",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Kotlin", "Microservices"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://careers.phonepe.com/sde-intern",
      description:
        "Work with senior engineers to enhance high-traffic payment services.\nHelp with coding, debugging, and performance testing of core flows.\nParticipate in technical reviews and learn production-grade practices.\nGreat role for final-year students seeking exposure to scale.",
    },
    {
      id: "job-12",
      title: "Frontend Intern",
      company: "Paytm",
      location: "Noida",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["React", "JavaScript", "CSS", "Testing Library"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://paytm.com/careers/frontend-intern",
      description:
        "Assist in building new UI experiences for Paytm web properties.\nImplement pixel-perfect interfaces that work reliably across devices.\nCollaborate with backend teams to integrate APIs and handle edge cases.\nIdeal for interns with strong front-end foundations and curiosity.",
    },
    {
      id: "job-13",
      title: "Data Analyst Intern",
      company: "Cognizant",
      location: "Pune",
      mode: "Remote",
      experience: "Fresher",
      skills: ["SQL", "Power BI", "Python"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://careers.cognizant.com/data-analyst-intern",
      description:
        "Support client projects with reporting and dashboard development.\nWork with consulting teams to translate business questions into metrics.\nClean, transform, and validate data from multiple systems.\nSuitable for candidates comfortable with analytical thinking and storytelling.",
    },
    {
      id: "job-14",
      title: "Junior Backend Developer",
      company: "Accenture",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "1-3",
      skills: ["Java", "Spring Boot", "Oracle DB"],
      source: "LinkedIn",
      postedDaysAgo: 7,
      salaryRange: "6–10 LPA",
      applyUrl: "https://www.accenture.com/in-en/careers/junior-backend",
      description:
        "Work on backend microservices for global enterprise clients.\nImplement features, bug fixes, and performance improvements.\nCollaborate with testers and DevOps teams to ship reliable releases.\nGood for engineers who enjoy structured delivery environments.",
    },
    {
      id: "job-15",
      title: "QA Intern",
      company: "Capgemini",
      location: "Mumbai",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Manual Testing", "JIRA", "API Testing"],
      source: "Indeed",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://www.capgemini.com/in-en/careers/qa-intern",
      description:
        "Assist QA teams in validating web and mobile application releases.\nDesign and execute test cases for new features and regression cycles.\nLog, track, and re-test defects across multiple environments.\nIdeal for detail-oriented graduates interested in quality engineering.",
    },
    {
      id: "job-16",
      title: "React Developer (1-3)",
      company: "Juspay",
      location: "Bengaluru",
      mode: "Remote",
      experience: "1-3",
      skills: ["React", "TypeScript", "FP Concepts"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "10–18 LPA",
      applyUrl: "https://juspay.in/careers/react-developer",
      description:
        "Build and maintain mission-critical payment UIs with a focus on safety.\nWork with functional programming paradigms to structure complex flows.\nCollaborate closely with backend and design teams on end-to-end features.\nBest for engineers who enjoy deep technical problem-solving.",
    },
    {
      id: "job-17",
      title: "SDE Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["C++", "Java", "Problem Solving"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://www.zoho.com/careers/sde-intern",
      description:
        "Contribute to core product modules used by global customers.\nImplement features under guidance, fix issues, and write unit tests.\nParticipate in internal hack days and learning sessions.\nSuitable for strong programmers comfortable with algorithms and systems.",
    },
    {
      id: "job-18",
      title: "Graduate Engineer Trainee",
      company: "IBM India",
      location: "Noida",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Cloud Basics", "Git"],
      source: "Naukri",
      postedDaysAgo: 9,
      salaryRange: "3–5 LPA",
      applyUrl: "https://www.ibm.com/in-en/employment/graduate-engineer",
      description:
        "Join IBM's early professional program and rotate across teams.\nSupport development, testing, and operations for enterprise clients.\nBuild foundational skills in cloud, DevOps, and secure coding.\nDesigned for fresh graduates with a strong learning mindset.",
    },
    {
      id: "job-19",
      title: "Python Developer (Fresher)",
      company: "Oracle India",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "Flask", "SQL"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.oracle.com/python-developer-fresher",
      description:
        "Support development of internal tools used by consulting teams.\nWork on small services, integration scripts, and utilities.\nCollaborate with senior engineers to improve code quality.\nIdeal for freshers familiar with REST APIs and relational databases.",
    },
    {
      id: "job-20",
      title: "Junior Backend Developer",
      company: "SAP Labs India",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Java", "Microservices", "Cloud Foundry"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "6–10 LPA",
      applyUrl: "https://jobs.sap.com/junior-backend-developer",
      description:
        "Help build and maintain SaaS modules for global customers.\nWork on microservices, integration layers, and performance improvements.\nParticipate in agile ceremonies and cross-team collaboration.\nWell-suited to engineers with experience in enterprise Java stacks.",
    },
    {
      id: "job-21",
      title: "Data Analyst Intern",
      company: "Razorpay",
      location: "Bengaluru",
      mode: "Remote",
      experience: "Fresher",
      skills: ["SQL", "Python", "Looker"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://razorpay.com/careers/data-analyst-intern",
      description:
        "Work with product analytics to study user and merchant behavior.\nBuild dashboards that help teams track payments and retention.\nExplore data to find anomalies, trends, and improvement opportunities.\nBest for analytically strong graduates with SQL proficiency.",
    },
    {
      id: "job-22",
      title: "React Developer (1-3)",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "1-3",
      skills: ["React", "Redux", "TypeScript"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "6–10 LPA",
      applyUrl: "https://www.zoho.com/careers/react-developer",
      description:
        "Build web interfaces for new and existing Zoho products.\nWrite reliable components and manage state across complex screens.\nCollaborate with backend and design teams on implementation details.\nIdeal for developers comfortable owning end-to-end UI features.",
    },
    {
      id: "job-23",
      title: "SDE Intern",
      company: "Freshworks",
      location: "Chennai",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Java", "Kotlin", "Microservices"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://careers.freshworks.com/sde-intern",
      description:
        "Assist with building reliable backend services for customer support products.\nHelp debug issues, write tests, and improve internal tooling.\nLearn cloud-native development from experienced engineers.\nSuitable for final-year students comfortable with one backend language.",
    },
    {
      id: "job-24",
      title: "Graduate Engineer Trainee",
      company: "Capgemini",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "SQL", "Basic Web"],
      source: "Indeed",
      postedDaysAgo: 9,
      salaryRange: "3–5 LPA",
      applyUrl: "https://www.capgemini.com/in-en/careers/graduate-engineer",
      description:
        "Start your career working on large-scale implementation projects.\nSupport configuration, customization, and basic development tasks.\nCollaborate with functional consultants and senior engineers.\nBest for fresh graduates open to working across domains and technologies.",
    },
    {
      id: "job-25",
      title: "Java Developer (0-1)",
      company: "Infosys",
      location: "Pune",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "REST"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.infosys.com/java-developer-0-1",
      description:
        "Join a delivery team to build and maintain Java-based systems.\nImplement modules under guidance and contribute to bug fixes.\nLearn deployment pipelines and basic monitoring tools.\nGood opportunity for recent graduates with Java training.",
    },
    {
      id: "job-26",
      title: "Python Developer (Fresher)",
      company: "Cognizant",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "Django", "REST"],
      source: "Indeed",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.cognizant.com/python-fresher",
      description:
        "Support simple microservices and integration scripts for client projects.\nWrite clean, maintainable Python code with adequate test coverage.\nWork with senior developers to understand system design decisions.\nIdeal for freshers who enjoy backend development.",
    },
    {
      id: "job-27",
      title: "Junior Backend Developer",
      company: "NovaHire",
      location: "Bengaluru",
      mode: "Remote",
      experience: "1-3",
      skills: ["Node.js", "MongoDB", "AWS"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "6–10 LPA",
      applyUrl: "https://novahire.in/careers/junior-backend",
      description:
        "Build candidate matching and scheduling services for a hiring platform.\nWork on APIs, cron jobs, and integrations with external tools.\nParticipate in design reviews, logging improvements, and refactoring.\nBest for developers comfortable working in a fast-moving startup.",
    },
    {
      id: "job-28",
      title: "React Developer (1-3)",
      company: "BetterStack India",
      location: "Remote - India",
      mode: "Remote",
      experience: "1-3",
      skills: ["React", "TypeScript", "GraphQL"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "10–18 LPA",
      applyUrl: "https://betterstack.io/careers/react-india",
      description:
        "Work on observability dashboards used by engineering teams worldwide.\nShip polished interfaces with attention to detail and performance.\nCollaborate with product and design to refine UX on complex screens.\nSuitable for engineers who care about clean code and user experience.",
    },
    {
      id: "job-29",
      title: "Data Analyst Intern",
      company: "TalentBay",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Tableau"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://talentbay.in/careers/data-analyst-intern",
      description:
        "Help build hiring funnels and reporting for recruitment campaigns.\nAnalyze candidate pipelines and hiring performance.\nPrepare weekly summaries for internal stakeholders.\nGreat for graduates interested in HR analytics and dashboards.",
    },
    {
      id: "job-30",
      title: "QA Intern",
      company: "CodeCraft Labs",
      location: "Pune",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Manual Testing", "Cypress", "API Testing"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://codecraftlabs.io/careers/qa-intern",
      description:
        "Test SaaS products used by international customers.\nDesign smoke tests, regression suites, and exploratory charters.\nWork closely with developers to understand architecture and edge cases.\nBest for detail-focused candidates who enjoy breaking things safely.",
    },
    {
      id: "job-31",
      title: "SDE Intern",
      company: "StackFoundry",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["JavaScript", "Node.js", "PostgreSQL"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://stackfoundry.in/careers/sde-intern",
      description:
        "Work with a small engineering team on B2B integrations.\nImplement endpoints, background jobs, and monitoring dashboards.\nParticipate in design sessions and post-incident reviews.\nIdeal for interns who want exposure to full-stack development.",
    },
    {
      id: "job-32",
      title: "Graduate Engineer Trainee",
      company: "BlueLeaf Systems",
      location: "Chennai",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Angular", "SQL"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "3–5 LPA",
      applyUrl: "https://blueleafsystems.in/careers/get",
      description:
        "Start on a product team building internal tooling for enterprises.\nContribute to both frontend and backend tasks as needed.\nReceive mentorship and structured feedback from seniors.\nGood for fresh graduates open to working across the stack.",
    },
    {
      id: "job-33",
      title: "Java Developer (0-1)",
      company: "Skyline Tech",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "MySQL"],
      source: "Indeed",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://skylinetech.in/careers/java-developer-junior",
      description:
        "Support design and implementation of backend modules.\nWrite REST APIs, unit tests, and basic integration tests.\nWork closely with senior engineers to understand architecture.\nIdeal for early-career developers in Java ecosystems.",
    },
    {
      id: "job-34",
      title: "Python Developer (Fresher)",
      company: "NextWave Digital",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Python", "FastAPI", "MongoDB"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "3–5 LPA",
      applyUrl: "https://nextwavedigital.in/careers/python-fresher",
      description:
        "Work on APIs and data processing pipelines for marketing campaigns.\nHelp design, implement, and monitor small microservices.\nCollaborate with analysts and campaign managers on data needs.\nSuited to freshers who enjoy data-heavy backend work.",
    },
    {
      id: "job-35",
      title: "React Developer (1-3)",
      company: "PixelBridge",
      location: "Pune",
      mode: "Remote",
      experience: "1-3",
      skills: ["React", "TypeScript", "Styled Components"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "6–10 LPA",
      applyUrl: "https://pixelbridge.io/careers/react-developer",
      description:
        "Develop admin and analytics interfaces for B2B SaaS products.\nFocus on consistency, design system usage, and accessibility.\nWork in a cross-functional squad with product and QA.\nIdeal for engineers who like owning UI modules end to end.",
    },
    {
      id: "job-36",
      title: "Data Analyst Intern",
      company: "DataWeave Labs",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Python", "Pandas", "SQL"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://dataweave.com/careers/data-analyst-intern",
      description:
        "Help collect and analyze e-commerce and pricing data at scale.\nBuild scripts and notebooks to clean, transform, and explore datasets.\nSummarize findings for internal stakeholders and product teams.\nGreat for freshers comfortable with Python-based data analysis.",
    },
    {
      id: "job-37",
      title: "QA Intern",
      company: "StackFoundry",
      location: "Bengaluru",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Manual Testing", "Postman", "Regression Testing"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://stackfoundry.in/careers/qa-intern",
      description:
        "Own verification of small features and bug fixes.\nDesign and execute regression cycles ahead of releases.\nLearn how to log, track, and triage issues effectively.\nIdeal for freshers looking to start in quality assurance.",
    },
    {
      id: "job-38",
      title: "SDE Intern",
      company: "NovaHire",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Node.js", "React", "MongoDB"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://novahire.in/careers/fullstack-intern",
      description:
        "Assist with full-stack features in a recruitment SaaS.\nImplement UI changes, API endpoints, and small utilities.\nParticipate in daily standups and sprint reviews.\nGood for interns who want experience across the stack.",
    },
    {
      id: "job-39",
      title: "Graduate Engineer Trainee",
      company: "PixelBridge",
      location: "Pune",
      mode: "Onsite",
      experience: "0-1",
      skills: ["JavaScript", "React", "SQL"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "3–5 LPA",
      applyUrl: "https://pixelbridge.io/careers/graduate-engineer",
      description:
        "Rotate across frontend, backend, and QA within a small team.\nWork on incremental improvements to existing SaaS modules.\nReceive structured feedback and guidance from senior engineers.\nSuited to fresh grads open to exploring multiple roles.",
    },
    {
      id: "job-40",
      title: "Java Developer (0-1)",
      company: "BlueLeaf Systems",
      location: "Chennai",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Spring", "REST APIs"],
      source: "LinkedIn",
      postedDaysAgo: 6,
      salaryRange: "3–5 LPA",
      applyUrl: "https://blueleafsystems.in/careers/java-junior",
      description:
        "Develop small services and utilities for enterprise integrations.\nWrite and maintain REST endpoints following established patterns.\nWork closely with technical leads on code reviews.\nIdeal for junior developers committed to improving their Java skills.",
    },
    {
      id: "job-41",
      title: "Python Developer (Fresher)",
      company: "DataWeave Labs",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Python", "Pandas", "Airflow"],
      source: "LinkedIn",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://dataweave.com/careers/python-fresher",
      description:
        "Help maintain data collection pipelines and ETL jobs.\nWrite Python scripts to parse and normalize external data.\nMonitor scheduled jobs and assist in handling failures.\nGreat for freshers who enjoy working close to data engineering.",
    },
    {
      id: "job-42",
      title: "React Developer (1-3)",
      company: "NextWave Digital",
      location: "Bengaluru",
      mode: "Remote",
      experience: "1-3",
      skills: ["React", "Next.js", "TypeScript"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://nextwavedigital.in/careers/react-developer",
      description:
        "Build marketing websites and dashboards for global clients.\nFocus on performance, SEO, and accessibility best practices.\nCollaborate with designers and copywriters on campaign launches.\nWell-suited to engineers who enjoy polished front-end work.",
    },
    {
      id: "job-43",
      title: "Data Analyst Intern",
      company: "NovaHire",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Looker Studio"],
      source: "Naukri",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://novahire.in/careers/data-analyst-intern",
      description:
        "Analyze job posting and candidate funnel data.\nPrepare weekly hiring reports for internal teams.\nExperiment with basic forecasting and trend analysis.\nIdeal for freshers exploring analytics in HR tech.",
    },
    {
      id: "job-44",
      title: "QA Intern",
      company: "BetterStack India",
      location: "Remote - India",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Manual Testing", "Playwright", "API Testing"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://betterstack.io/careers/qa-intern-india",
      description:
        "Test monitoring and logging products used by developers worldwide.\nWork on test suites for web dashboards and API endpoints.\nDocument issues clearly with steps, logs, and screenshots.\nSuited to detail-oriented interns who value reliability.",
    },
    {
      id: "job-45",
      title: "SDE Intern",
      company: "TalentBay",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Spring Boot", "PostgreSQL"],
      source: "Indeed",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://talentbay.in/careers/sde-intern",
      description:
        "Contribute to applicant tracking and reporting modules.\nImplement backend endpoints, validations, and simple workflows.\nCollaborate with QA and product teams on feature releases.\nIdeal for freshers who enjoy backend-heavy work.",
    },
    {
      id: "job-46",
      title: "Graduate Engineer Trainee",
      company: "StackFoundry",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["JavaScript", "React", "Node.js"],
      source: "LinkedIn",
      postedDaysAgo: 6,
      salaryRange: "3–5 LPA",
      applyUrl: "https://stackfoundry.in/careers/graduate-engineer",
      description:
        "Work with mentors across frontend and backend teams.\nPick up small tasks in product, infra, and QA areas.\nLearn modern tooling, deployment, and monitoring practices.\nGreat for graduates who want broad exposure in a startup.",
    },
    {
      id: "job-47",
      title: "Java Developer (0-1)",
      company: "TalentBay",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "REST"],
      source: "Naukri",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://talentbay.in/careers/java-developer-junior",
      description:
        "Implement and maintain backend modules for recruitment workflows.\nParticipate in daily standups, code reviews, and release planning.\nWrite clear documentation for APIs and integration points.\nIdeal for juniors who enjoy iterative product development.",
    },
    {
      id: "job-48",
      title: "Python Developer (Fresher)",
      company: "PixelBridge",
      location: "Pune",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "Flask", "PostgreSQL"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "3–5 LPA",
      applyUrl: "https://pixelbridge.io/careers/python-fresher",
      description:
        "Support backend APIs for reporting and analytics modules.\nFix bugs, write tests, and improve internal tooling.\nCollaborate with analysts on data requirements and schema changes.\nSuited to freshers who like small, focused teams.",
    },
    {
      id: "job-49",
      title: "React Developer (1-3)",
      company: "BlueLeaf Systems",
      location: "Chennai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Redux", "REST APIs"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://blueleafsystems.in/careers/react-mid",
      description:
        "Build internal dashboards and configuration tools for enterprise clients.\nEnsure UI consistency with the shared design system.\nWork closely with backend teams to design API contracts.\nIdeal for developers who enjoy structured, predictable work.",
    },
    {
      id: "job-50",
      title: "Data Analyst Intern",
      company: "NextWave Digital",
      location: "Bengaluru",
      mode: "Remote",
      experience: "Fresher",
      skills: ["SQL", "Google Sheets", "Data Studio"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://nextwavedigital.in/careers/data-analyst-intern",
      description:
        "Support marketing teams with campaign and funnel analysis.\nBuild recurring performance reports and simple dashboards.\nWork with senior analysts to define meaningful metrics.\nGood for freshers transitioning into marketing analytics.",
    },
    {
      id: "job-51",
      title: "QA Intern",
      company: "NovaHire",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Manual Testing", "TestRail", "API Testing"],
      source: "Naukri",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://novahire.in/careers/qa-intern-onsite",
      description:
        "Test new features across web and mobile clients.\nMaintain structured test cases and regression checklists.\nCollaborate with engineers to reproduce and debug defects.\nIdeal for detail-oriented graduates entering QA.",
    },
    {
      id: "job-52",
      title: "SDE Intern",
      company: "BetterStack India",
      location: "Remote - India",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Go", "PostgreSQL", "Docker"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://betterstack.io/careers/sde-intern-india",
      description:
        "Assist in building observability tooling for developers.\nImplement small backend features and improve internal tools.\nParticipate in code reviews and incident follow-ups.\nBest for interns comfortable reading and writing production code.",
    },
    {
      id: "job-53",
      title: "Graduate Engineer Trainee",
      company: "DataWeave Labs",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Python", "SQL", "Linux"],
      source: "LinkedIn",
      postedDaysAgo: 7,
      salaryRange: "3–5 LPA",
      applyUrl: "https://dataweave.com/careers/graduate-engineer",
      description:
        "Rotate between data engineering, QA, and platform teams.\nSupport ingestion, processing, and validation of external datasets.\nLearn best practices for observability and reliability.\nGreat for graduates exploring data-focused engineering roles.",
    },
    {
      id: "job-54",
      title: "Java Developer (0-1)",
      company: "NextWave Digital",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "MySQL"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "3–5 LPA",
      applyUrl: "https://nextwavedigital.in/careers/java-developer-junior",
      description:
        "Work on API layers for reporting and client integrations.\nHelp with bug fixes, logging improvements, and minor features.\nCollaborate with senior engineers on design and code reviews.\nIdeal for juniors comfortable with RESTful services.",
    },
    {
      id: "job-55",
      title: "Python Developer (Fresher)",
      company: "NovaHire",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "FastAPI", "PostgreSQL"],
      source: "Naukri",
      postedDaysAgo: 9,
      salaryRange: "3–5 LPA",
      applyUrl: "https://novahire.in/careers/python-fresher",
      description:
        "Help extend APIs used by recruiters and hiring managers.\nWrite clean, well-documented endpoints and background tasks.\nWork within a small team that values readable code.\nSuitable for freshers with strong Python fundamentals.",
    },
    {
      id: "job-56",
      title: "React Developer (1-3)",
      company: "TalentBay",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "TypeScript", "Redux"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://talentbay.in/careers/react-developer",
      description:
        "Build recruiter and candidate dashboards with a clean, modern UI.\nEnsure responsive layouts and accessible interactions.\nCollaborate with backend engineers on API integration.\nBest for engineers with prior React production experience.",
    },
    {
      id: "job-57",
      title: "Data Analyst Intern",
      company: "BlueLeaf Systems",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Power BI"],
      source: "Indeed",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://blueleafsystems.in/careers/data-analyst-intern",
      description:
        "Support reporting needs for internal and client projects.\nBuild dashboards that summarize operational and financial metrics.\nWork with business stakeholders to refine requirements.\nIdeal for freshers who enjoy structured analysis.",
    },
    {
      id: "job-58",
      title: "QA Intern",
      company: "NextWave Digital",
      location: "Bengaluru",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Manual Testing", "Cypress", "Regression Testing"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://nextwavedigital.in/careers/qa-intern",
      description:
        "Test marketing websites and web apps before launch.\nMaintain regression suites and smoke test checklists.\nCollaborate with developers to refine acceptance criteria.\nGreat for freshers who enjoy breaking flows thoughtfully.",
    },
    {
      id: "job-59",
      title: "SDE Intern",
      company: "BlueLeaf Systems",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Spring Boot", "Angular"],
      source: "Naukri",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://blueleafsystems.in/careers/sde-intern",
      description:
        "Assist with full-stack features in enterprise web portals.\nImplement UI screens, services, and tests under guidance.\nParticipate in code reviews to learn best practices.\nSuitable for final-year students who enjoy end-to-end work.",
    },
    {
      id: "job-60",
      title: "Graduate Engineer Trainee",
      company: "NovaHire",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["JavaScript", "React", "Node.js"],
      source: "Indeed",
      postedDaysAgo: 10,
      salaryRange: "3–5 LPA",
      applyUrl: "https://novahire.in/careers/graduate-engineer-trainee",
      description:
        "Join a structured program to learn full-stack development.\nContribute to product, integrations, and reporting modules.\nReceive mentorship, feedback, and growth discussions regularly.\nIdeal for early-career engineers building a broad foundation.",
    },
  ];
})();

